FROM adoptopenjdk/openjdk14
RUN mkdir /opt/ogema
WORKDIR /opt/ogema
ADD https://github.com/ogema/ogema-launcher/releases/download/v1.3.1/ogema-launcher-1.3.1.jar ogema-launcher.jar
COPY config/config* config/
RUN java -jar ogema-launcher.jar -b --config config/config.xml config/config11_fragment.xml
COPY config config
EXPOSE 8080
EXPOSE 8443
CMD java \
    -Djavax.xml.bind.JAXBContextFactory=org.eclipse.persistence.jaxb.JAXBContextFactory \
    -Dorg.osgi.framework.security=osgi -Djava.security.policy=config/all.policy -Dorg.ogema.security=on \
    -jar ogema-launcher.jar \
    --config config/config.xml config/config11_fragment.xml --security config/ogema.policy --use-rundir-only
